### ISSUE TITLE
Forgotten layout not displayed correctly

### ISSUE THREAD

**Issue by rongoree** [zbluebugz/CnC-TA-Opt#10]
Some Forgotten layouts do not load correctly. They partially load but then hit an error and the rest of the layout fails to be processed and displayed. The layout linked below is an example that I found that demonstrates this problem, it loads correctly in [CNC-Opt](http://cncopt.com/?map=3|F|G|Base|37u37r38b38r37u..38q37y37r38ht37r37h....37r37h37r37b....37w.37b....37v.....c..38nc....37n.38s37s38s..37h..37s38n37v37h...37r.37s38n37s.37r37q37q37r38v37o.37g.38mhhh37r37o37g.37ul37o37b37b37b37b.38b38b38b37g.l37s.37yll37gk.37n.37m37g37v37g37b37u.37v.37gj37yjjkkk37rh37q.37f38n37b37b37f37fh37q.ll.....65s65q65q65s......65m65m65m......65j65j65c65o65o.65a65a.65k65f65f|9000000|9000000|9000000|172|172|176|172|newEconomy
) but not in [CNC-TA-Opt](http://www.cnctaopt.com/?map=3~F~G~Base~37u37r38b38r37u..38q37y37r38ht37r37h....37r37h37r37b....37w.37b....37v.....c..38nc....37n.38s37s38s..37h..37s38n37v37h...37r.37s38n37s.37r37q37q37r38v37o.37g.38mhhh37r37o37g.37ul37o37b37b37b37b.38b38b38b37g.l37s.37yll37gk.37n.37m37g37v37g37b37u.37v.37gj37yjjkkk37rh37q.37f38n37b37b37f37fh37q.ll.....65s65q65q65s......65m65m65m......65j65j65c65o65o.65a65a.65k65f65f~9000000~9000000~9000000~172~172~176~172~newEconomy).

I believe that the problem may be caused by the fact that the "Unique buildings can't be placed next to each other" restriction is being enforced on Forgotten layouts also. That restriction should only be applied to player base layouts because the Forgotten layouts can have their unique buildings right next each other.

P.S. - I really like your site and of the various CNC-Opt replacements that I have tried I think it is the best.

Ron

**Comment by zbluebugz** [comment]
Thanks for the feedback.

I didn't realise that the The Forgotten have different rules for where items can go.

Will fix by amdending the code accordingly.

**Comment by zbluebugz** [comment]
Fixed.
