### ISSUE TITLE
Change in max levels for new worlds

### ISSUE THREAD

**Issue by zbluebugz** [zbluebugz/CnC-TA-Opt#21]
Worlds created since 10th April 2020 have a new max level of 80, instead of 65.

let maxLevel = 80 ;
if ( WorldID < 415 ) {
  maxLevel = 65 ;
}

**Comment by leo7044** [comment]
Hiho,
how is the current state? When do you plan to support buildings, def and offense until level 80?

Greetings
Leo

**Comment by zbluebugz** [comment]
Currently working on a new version which has some new features.

Currently, I'm in the middle of adding language support. 

Regarding, level 80, it is next on my ToDo list (just need to check figures and if possible to detect which worlds have level 80)

Hope to go live at end of January 2021.

**Comment by leo7044** [comment]
If it helps: On a world you can ask with `ClientLib.Data.MainData.GetInstance().get_Server().get_PlayerUpgradeCap();` which MaxLevel on a world exists (65, 75 or 80). But in general you could allow Level 80 on each world.
The upgrade-costs and gains should be exponential (like from 12 to 65).

If you should not know the API: https://cncapp06.alliances.commandandconquer.com/320/ClientLib.js.txt

I'm looking forward to your new version :)

**Comment by zbluebugz** [comment]
Thanks for the tip and link to the API - muchly appreciated!

**Comment by leo7044** [comment]
You are welcome. If you need more, just give me a ping. :)

**Comment by zbluebugz** [comment]
Version 3:
- Max levels implemenented - 65/75/80
