### ISSUE TITLE
Beta-Script redirects to empty Website

### ISSUE THREAD

**Issue by leo7044** [zbluebugz/CnC-TA-Opt#23]
Hiho,

http://www.cnctaopt.com/beta/ is forbidden and http://www.cnctaopt.com/beta/index.html redirects to http://www.cnctaopt.com/ with an empty base. The Button InGame just redirects to http://www.cnctaopt.com/ too.

Greetings
Leo

**Comment by zbluebugz** [comment]
I had to take it down due to a couple of bugs. Now back up and ready for testing.
