### ISSUE TITLE
Production-Values not maching to 100% (game vs. cnctaopt)

### ISSUE THREAD

**Issue by leo7044** [zbluebugz/CnC-TA-Opt#25]
Picture of "bug":
- https://prnt.sc/xxh34i

Link to base:
- http://cnctaopt.com/ydpuy

Facts:
- Package-Production is correct
- if I add silos I get a higher production in cnctaopt than real

Hypothesis:
- Wrong data for silos? Maybe only below level 12?

**Comment by zbluebugz** [comment]
Thanks for the screen shot.

Issue: Connection rate inaccurate for harvester level < 13.

Fixed. Harvester's connection rate data updated and pushed into production.

**Comment by zbluebugz** [comment]
Additional info: Tiberian 49 (#423)
