### ISSUE TITLE
New Update

### ISSUE THREAD

**Issue by TimmyC9527** [zbluebugz/CnC-TA-Opt#26]
hi,

the new update feels very hard to use, it is not easy to use compared to the previous version.

loss of features like 
- highlighting multiple squares when planning base layout, if i was to plan where to put my power reactors then i would like to be able to highlight multiple boxes in the 1 time to plan where they can go.
- changing the level of structure with the number pad.
- instant view of the base productions
- package production view / continuous production view
- the screen is also zoomed in so its harder to view the base as a whole

**Comment by zbluebugz** [comment]
> changing the level of structure with the number pad.

Will make the Level box adjustable via SELECT box (as per previous version of the site)

**Comment by zbluebugz** [comment]
> the screen is also zoomed in so its harder to view the base as a whole

@TimmyC9527 What screen resolution do you have/use?

Will tweak the screen sizing code.

**Comment by zbluebugz** [comment]
> highlighting multiple squares when planning base layout, if i was to plan where to put my power reactors then i would like to be able to highlight multiple boxes in the 1 time to plan where they can go.

You can do this in a couple of different ways:
Method 1:
- Click on an item from the table of items (e.g. Power Plant) so it becomes selected (green background) - it causes this item to be "sticky".
- Click on the layout cells you want that selected item to be copied into.
- Click on the item again in the table of items to make it un-sticky or select another item from the table.

Method 2:
- Mouse hover over a layout cell and press the hot-key for the item to place into that cell - e.g. pressing "P" (for power plant) while mouse is hovering over cell #32
- Repeat for next layout cell


Unlikely to implement the multiple selection of layout cells - will review at a later date.

**Comment by zbluebugz** [comment]
> instant view of the base productions
> package production view / continuous production view

ATM, this information is shown when hovering over the Tiberium, Crystal, Power and Credits icons above the base's layout grid.

If you click on the "Settings" button, you'll see the "Base layout: Settings" dialog box. In this box, there the option "Set resource production baseline:" - this will expand the information bubble boxes.


Will add the table of production (as per previous version of the site) back in and allow users to toggle the display of this table.

**Comment by zbluebugz** [comment]
> 
> > changing the level of structure with the number pad.
> 
> Will make the Level box adjustable via SELECT box (as per previous version of the site)

DONE.

**Comment by zbluebugz** [comment]
> 
> > the screen is also zoomed in so its harder to view the base as a whole
> 
> @TimmyC9527 What screen resolution do you have/use?
> 
> Will tweak the screen sizing code.

DONE.

**Comment by zbluebugz** [comment]
> 
> > instant view of the base productions
> > package production view / continuous production view
> 
> ATM, this information is shown when hovering over the Tiberium, Crystal, Power and Credits icons above the base's layout grid.
> 
> If you click on the "Settings" button, you'll see the "Base layout: Settings" dialog box. In this box, there the option "Set resource production baseline:" - this will expand the information bubble boxes.
> 
> Will add the table of production (as per previous version of the site) back in and allow users to toggle the display of this table.

Added table. Removed bubble boxes from overall rss summary boxes.

**Comment by TimmyC9527** [comment]
hi, the production values dont change when i change the level of the structures?

**Comment by zbluebugz** [comment]
@TimmyC9527 Can you post the cnctaopt link so I can check it out.

Additional questions:
- Which resource type not changing?
- How are you changing the levels?

**Comment by zbluebugz** [comment]
Also, which resource type not changing?

**Comment by TimmyC9527** [comment]
http://cnctaopt.com/7fLNS

so i tried to test it on a camp, for potential new base, 
I highlight slot for silo, add in harvester ok. 
I also activated the baseline. Then i change silo from 20 to level 50, no change? it does not update the production values, same goes with power accumulator and every other structure.

i highlight the slot then the drop down box appears, I type in the number.

**Comment by zbluebugz** [comment]
If the base's Faction is FA (Forgotten Army), then no calculations are done.

However, if the Faction is GDI or NOD:
- If the SELECT box is is still showing the drop-down list after you have typed in a new value but haven't pressed the Enter/Tab key or clicked out, then nothing changes. 
  - The SELECT's drop-down list must be closed/collapsed in order for the browser to trigger a change event (standard browser behaviour).
  - You need to either press Enter or Tab or Click on the number or outside of the SELECT box in order for the browser to trigger a change event (default behaviour in browsers)

- If the SELECT box is not showing the drop-down list as you type in a new value, the figures will change (default behaviour in browsers)

**Comment by TimmyC9527** [comment]
Ok thanks, only tab method works for me on chrome - using the drop box, pressing Enter or clicking outside the select box does not work for me - the values dont change.

Iv just tested this on firefox, it works all 3 ways, using drop box, pressing enter + pressing tab.
thanks

**Comment by zbluebugz** [comment]
Thanks for extra hint - Chrome isn't sending the change events properly.

Code will to be tweaked to make Chrome behave.

**Comment by zbluebugz** [comment]
Amended the code to listen to the SELECT's change event.

Tested in Chrome and Firefox.

**Comment by TimmyC9527** [comment]
thanks, everything seems fine now!

**Comment by zbluebugz** [comment]
Thanks for the feedback :-)
