### ISSUE TITLE
Can't delete on macOS / no Del key on the keyboard

### ISSUE THREAD

**Issue by Attome83** [zbluebugz/CnC-TA-Opt#27]
Hi,

First thanks for the great job you guys are dooing.

So the issue I got on Mac, I don't manage to delete a building from the layout or a def unit or an offense unit.

I've tryed almost all the keys of my key board, try with ctrl+key, alt+fey or shift+key and won't work.
It's pretty annoying I have to say but still very happy about this tool.

Thanks

M.

**Comment by zbluebugz** [comment]
Code has been updated to allow an alternative key to be used for deleting item(s).

You can use the "." (dot) key to delete items.

You will need to force your browser to do a full/hard-refresh of the website's page to ensure the browser has the latest code. (Not too sure what the hot-keys are for this on a Mac, but for Windows, it is Ctrl + F5).

Thanks for the compliments.

**Comment by zbluebugz** [comment]
@Attome83 Question: Does key combination "fn" + "Backspace" work?

**Comment by Attome83** [comment]
> @Attome83 Question: Does key combination "fn" + "Backspace" work?

Hi, fn+backspace is working and the "dot" key also now

Thank you; a great quick answer

Cheers

**Comment by zbluebugz** [comment]
Good to know that the "fn" + "backspace" works as well.

Thanks for the feedback.
