### ISSUE TITLE
GM_log optional

### ISSUE THREAD

**Issue by netquik** [zbluebugz/CnC-TA-Opt#29]
Hi @zbluebugz and thanks for your work.
Is possible to change

GM_log(e) in the catch for try run all code

with 

    if (typeof console != 'undefined') console.log(e);
	else if (window.opera) opera.postError(e);
	else if (typeof GM_log != 'undefined') GM_log(e);

so it will not throw ReferenceError if the script is used outside Grease/TamperMonkey?  

Thanks

**Comment by zbluebugz** [comment]
Changes made as per request.

Thanks for including this in your cncta's script pack.
