### ISSUE TITLE
unsafeWindow on firefox and version numbering

### ISSUE THREAD

**Issue by netquik** [zbluebugz/CnC-TA-Opt#30]
Hi again.
For using the script outside greasemonkey on Firefox
unsafeWindow can't be used.

In the past i modified cncopt scripts using simply "window".

When including it in my pack i have to do same modification or Firefox users could not use it.

As it is used only for version numbering (well it actually set it to 1.0.3 not to 1.0.7.5) i think it can be removed at all leaving "CnCTAOpt Link Button loaded" or just add a version number variable before calling  
                console.log("CnCTAOpt Link Button v" + window.__cnctaoptv3_version + " loaded");
in function cnctaopt3_create() 

Thanks

**Comment by netquik** [comment]
try {
    
    (function () {
        const cnctaopt_v3 = function () {
            // cnctaopt version
            const cnctaoptv3_version = "1.0.7.5";
            // base / defense / offense - map units with cnctaopt's hotkeys.
            const base_unit_map = {
                /* GDI Buildings */
                "GDI_Construction Yard": "y",   // construction yard
                "GDI_Power Plant": "p",         // power plant
                "GDI_Refinery": "r",            // refinery
                // "GDI_Trade Center": "u",
                "GDI_Silo": "s",                // silo


then

```
 function cnctaopt3_create() {
                console.log("CnCTAOpt Link Button v" + cnctaoptv3_version + " loaded");
                const cnctaopt = {
```


this change would avoid any issues

**Comment by zbluebugz** [comment]
Will apply fix in a few hours and test in Firefox and Chrome.

**Comment by netquik** [comment]
thanks also please double check

else if (typeof GM_log != 'undefined') GM_log(e);

need to check existence of GM_log in all occurrences of GM_log (looking at you last update)

Thanks

**Comment by zbluebugz** [comment]
I have revised the script code and created a beta version: (CnC-TA-Opt/beta/CnCTAOpt.link.beta.user.js)
- removed GM_log
- removed unsafewindow
- simplified error trapping
- simplified checkIfLoaded

If this works for you, I'll push it into production.

**Comment by netquik** [comment]
the code works as expected.
I did'n want you to remove try catch and logging.. but ok.
changes are as i suggested.. but you could only replace GM_log with the check
in any case it works

thanks

**Comment by zbluebugz** [comment]
Thanks for the feedback.

Changes have been published.

**Comment by netquik** [comment]
good. many thanks @zbluebugz . maybe the code would be more compatible now in many specific cases.
thanks again.
