### ISSUE TITLE
cnctaopt button

### ISSUE THREAD

**Issue by TimmyC9527** [zbluebugz/CnC-TA-Opt#31]
cnctaopt button is gone in chrome browser?

button is available on firefox though

**Comment by zbluebugz** [comment]
Issue with the SOO pack. netquik who maintains the SOO pack has been notified by another user and has applied a fix. Currently waiting for approval by Google.

SOO's home page: https://github.com/netquik/CnCTA-SoO-SCRIPT-PACK


As a temporary workaround, you can install the stand-alone version available from here or netquik's github.

Note: The stand-alone version is not affected by the issue with SOO pack.
