### ISSUE TITLE
Powerplant upgrade costs

### ISSUE THREAD

**Issue by deadmeat82** [zbluebugz/CnC-TA-Opt#32]
Hi, I just noticed that the cost for upgrading a powerplant seems to be a level lower in the upgrade priority window but only when looking at credit priority. 

This screenshot shows the issue [https://i.imgur.com/hg5fX3R.png] and shows the cost of levelling a powerplant from 18 to 19 as 871,429 tib in the upgrade costs window, but the same powerplant in the upgrade priority window shows as 660,174 tib to upgrade from 18 to 19, but this is the cost to level from 17 to 18.

If I change upgrade priority window to power it shows correctly [https://i.imgur.com/GIZl7Xo.png].

Awesome work btw and thanks for your continued development!

**Comment by zbluebugz** [comment]
Good spotting - I'll apply a fix to the code soon.

Thanks for the compliments!

**Comment by zbluebugz** [comment]
Priority Upgrade component: Power Plant's Costs for Credits production has been updated.
