### ISSUE TITLE
Command and Conquer: Tiberium Alliances Base Layout Tools

### ISSUE THREAD

**Issue by Cavalier0007** [zbluebugz/CnC-TA-Opt#34]
Could offense repair time be added to Command and Conquer: Tiberium Alliances Base Layout Tool?  Other tools do provide a capability that could be ported over to this tool.  This would make it possible to find an optimal offense based on a desired repair time.  By playing around with different configurations, you can much more easily find an affordable, optimized offense.

https://www.cnctaopt.com/

Offense Layout Tool
![Example](https://user-images.githubusercontent.com/122232222/211216730-c19fe9ef-5d81-478f-999a-e0cae7c22fe4.png)

Using Info from here
![From here](https://user-images.githubusercontent.com/122232222/211216815-d2ff958f-487f-4b7f-a049-a90100bc1d5f.png)

Thanks
Cavalier007 in TA

**Comment by zbluebugz** [comment]
Will investigate if I can extract the relevant data and figure out how to do the calculations.

**Comment by Cavalier0007** [comment]
Here’s another option that might prove useful.  I really appreciate your taking a look.


[Screenshot by Lightshot (prnt.sc)]

https://prnt.sc/W7dy191COvou
